export const STANDARD_FIELDS = {
  transaction_date: 'Tanggal Transaksi',
  transaction_time: 'Jam Transaksi',
  transaction_id: 'Nomor Transaksi',
  product_id: 'SKU / Kode Produk',
  product_name: 'Nama Produk',
  category: 'Kategori Produk',
  brand: 'Merek / Brand',
  variant: 'Varian',
  quantity: 'Jumlah Barang',
  unit_price: 'Harga Satuan',
  discount_amount: 'Diskon',
  shipping_fee: 'Biaya Kirim',
  cogs: 'Harga Pokok (HPP)',
  gross_profit: 'Laba Kotor',
  sales_amount: 'Total Penjualan',
  return_amount: 'Nilai Retur',
  return_quantity: 'Qty Retur',
  payment_method: 'Metode Pembayaran',
  payment_status: 'Status Pesanan',
  customer_name: 'Nama Pelanggan',
  customer_id: 'ID Pelanggan',
  sales_channel: 'Channel Penjualan',
  destination_city: 'Kota Pengiriman',
  branch: 'Cabang',
  staff_name: 'Nama Staff/Karyawan',
  staff_commission: 'Komisi Staff',
  supplier: 'Supplier / Pemasok',
  rating: 'Rating/Ulasan',
  duration_mins: 'Durasi Layanan',
  tax: 'Pajak / PPN',
  service_charge: 'Service Charge',
  platform_fee: 'Biaya Platform',
  promo_code: 'Kode Promo / Voucher',
  customer_type: 'Tipe Pelanggan',
  expense_amount: 'Beban Operasional Lain',
  order_type: 'Tipe Pesanan',
  payment_provider: 'Penyedia Pembayaran',
  shipping_courier: 'Kurir Pengiriman',
  table_number: 'Nomor Meja',
};

export const FIELD_SYNONYMS = {
  transaction_date: ['tanggal', 'tgl', 'tgl transaksi', 'tanggal order', 'order date', 'trx date', 'completed date', 'date', 'tgl pesanan', 'tanggal booking'],
  transaction_time: ['jam', 'waktu', 'jam transaksi', 'waktu transaksi', 'time', 'jam mulai', 'jam order'],
  transaction_id: ['invoice', 'no invoice', 'nomor nota', 'no nota', 'transaction id', 'order id', 'id', 'nomor invoice', 'kode booking'],
  product_id: ['sku', 'kode barang', 'kode produk', 'product id', 'item code', 'kode menu'],
  product_name: ['produk', 'nama produk', 'barang', 'nama barang', 'nama item', 'item', 'product name', 'product', 'menu', 'nama menu', 'layanan'],
  category: ['kategori', 'kategori produk', 'category', 'jenis', 'jenis produk', 'tipe', 'kategori menu', 'product category', 'kategori layanan', 'jenis menu', 'grup', 'group', 'departemen'],
  brand: ['merek', 'brand', 'merk'],
  variant: ['varian', 'variant', 'ukuran', 'size', 'warna', 'color'],
  quantity: ['qty', 'quantity', 'jumlah', 'unit', 'pcs', 'jml', 'unit terjual'],
  unit_price: ['harga', 'harga jual', 'unit price', 'price', 'harga satuan', 'harga layanan'],
  discount_amount: ['diskon', 'potongan', 'discount', 'potongan harga', 'discount amount', 'seller discount', 'voucher', 'disc item', 'promo', 'disc'],
  shipping_fee: ['ongkir', 'biaya kirim', 'shipping', 'shipping fee', 'ongkos kirim', 'buyer shipping'],
  cogs: ['cogs', 'hpp', 'modal', 'harga beli', 'harga pokok', 'biaya variabel', 'cost', 'unit cost'],
  gross_profit: ['laba kotor', 'profit', 'gross profit', 'pendapatan bersih', 'net revenue', 'margin', 'laba'],
  sales_amount: ['total', 'grand total', 'omzet', 'penjualan', 'revenue', 'amount', 'total bayar', 'total netto', 'subtotal', 'nilai penjualan', 'nilai transaksi', 'gross sales', 'gross merchandise value', 'gross revenue', 'gross', 'netto', 'total tagihan', 'total order'],
  return_amount: ['retur', 'refund', 'nilai retur', 'return amount', 'refund amount'],
  return_quantity: ['qty retur', 'jumlah retur', 'return quantity'],
  payment_method: ['metode pembayaran', 'pembayaran', 'payment', 'tipe pembayaran', 'cara bayar', 'metode bayar', 'bayar via', 'via', 'jenis pembayaran'],
  payment_status: ['status pesanan', 'payment status', 'status pembayaran', 'status', 'order status', 'status kunjungan', 'status order', 'status trx'],
  customer_name: ['customer', 'pelanggan', 'pembeli', 'nama customer', 'nama member', 'nama pelanggan'],
  customer_id: ['id pelanggan', 'customer id', 'member id', 'id customer'],
  sales_channel: ['channel', 'marketplace', 'sumber penjualan', 'platform', 'sales channel', 'sumber', 'channel penjualan', 'sumber order', 'sumber booking'],
  destination_city: ['kota pengiriman', 'destination city', 'kota', 'city', 'tujuan'],
  branch: ['cabang', 'toko', 'outlet', 'lokasi', 'branch'],
  staff_name: ['staff', 'nama staff', 'kasir', 'cashier', 'sales', 'sales person', 'karyawan', 'stylist', 'therapist'],
  staff_commission: ['komisi', 'komisi staff', 'insentif', 'bonus', 'tip'],
  supplier: ['supplier', 'pemasok', 'vendor', 'distributor'],
  rating: ['rating', 'penilaian', 'bintang', 'ulasan', 'review'],
  duration_mins: ['durasi', 'durasi layanan', 'durasi (menit)', 'waktu layanan', 'menit'],
  tax: ['ppn', 'pajak', 'tax', 'pb1'],
  service_charge: ['service', 'service charge', 'biaya layanan', 'layanan'],
  platform_fee: ['fee platform', 'biaya aplikasi', 'platform fee', 'mdr'],
  promo_code: ['kode promo', 'promo code', 'voucher code', 'kode voucher', 'kupon', 'coupon', 'kode diskon'],
  customer_type: ['tipe pelanggan', 'customer type', 'member type', 'jenis pelanggan', 'membership', 'grup pelanggan', 'tipe member', 'kategori pelanggan'],
  expense_amount: ['pengeluaran', 'operational expense', 'biaya operasional', 'beban', 'expense', 'opex', 'pengeluaran lain', 'biaya opex', 'biaya lain'],
  order_type: ['tipe order', 'order type', 'layanan', 'dine in', 'takeaway', 'delivery', 'tipe layanan', 'jenis layanan'],
  payment_provider: ['penyedia pembayaran', 'payment provider', 'bank', 'shopeepay', 'gopay', 'ovo', 'bca', 'mandiri', 'dana', 'linkaja', 'qris', 'tunai', 'cash', 'gateway', 'payment gateway'],
  shipping_courier: ['kurir pengiriman', 'kurir', 'ekspedisi', 'courier', 'shipping courier', 'jne', 'jnt', 'sicepat', 'gosend', 'grabexpress', 'pos', 'tiki', 'wahana', 'anteraja'],
  table_number: ['nomor meja', 'no meja', 'meja', 'table number', 'table no', 'table', 'nomor meja/area'],
};
