import XLSX from 'xlsx';
import fs from 'fs';

const excelDateToISOString = (val) => {
  if (typeof val === 'number') {
    // Excel base date is 1899-12-30 due to leap year bug in Lotus 1-2-3
    const date = new Date((val - 25569) * 86400 * 1000);
    return date.toISOString().split('T')[0];
  }
  return String(val);
};

const getCustomerType = (id) => {
  if (!id) return 'Umum';
  const num = parseInt(id.replace(/\D/g, ''), 10);
  if (isNaN(num)) return 'Umum';
  if (num % 5 === 0) return 'VIP';
  if (num % 2 === 0) return 'Member';
  return 'Umum';
};

try {
  const workbook = XLSX.readFile('dataset_umkm_retail_kompleks_jan_mei_2026.xlsx');
  const worksheet = workbook.Sheets['Data_Clean'];
  
  if (!worksheet) {
    throw new Error('Data_Clean sheet not found in workbook!');
  }
  
  // Convert sheet to 2D array
  const rows = XLSX.utils.sheet_to_json(worksheet, { header: 1 });
  
  // Header row is index 3
  const headers = rows[3];
  console.log('Detected Headers:', headers);
  
  const colIndex = (name) => headers.indexOf(name);
  
  const dateIdx = colIndex('transaction_date');
  const txIdIdx = colIndex('transaction_id');
  const prodNameIdx = colIndex('product_name');
  const catIdx = colIndex('category');
  const brandIdx = colIndex('brand');
  const qtyIdx = colIndex('quantity');
  const discIdx = colIndex('discount_amount');
  const salesIdx = colIndex('sales_amount');
  const cogsIdx = colIndex('cogs');
  const custIdIdx = colIndex('customer_id');
  const channelIdx = colIndex('sales_channel');
  const branchIdx = colIndex('branch');
  const cashierIdx = colIndex('cashier');
  const payMethodIdx = colIndex('payment_method');
  const isValidIdx = colIndex('is_valid_sale');

  const parsedData = [];
  
  // Start from row 4 (index 4)
  for (let i = 4; i < rows.length; i++) {
    const row = rows[i];
    if (!row || row.length === 0) continue;
    
    // Check validity
    const isValid = row[isValidIdx];
    if (isValid !== 1) continue;
    
    const rawDate = row[dateIdx];
    const dateStr = excelDateToISOString(rawDate);
    
    const product = row[prodNameIdx];
    const category = row[catIdx];
    const qty = Number(row[qtyIdx] || 0);
    const sales = Number(row[salesIdx] || 0);
    const cogs = Number(row[cogsIdx] || 0);
    const discount = Number(row[discIdx] || 0);
    const channel = row[channelIdx] || 'Kasir Toko';
    const payMethod = row[payMethodIdx] || 'Tunai';
    const customerId = row[custIdIdx] || '';
    const brand = row[brandIdx] || 'Biasa';
    const cashier = row[cashierIdx] || 'Kasir';
    const branch = row[branchIdx] || 'Toko Utama';

    // Map order type
    const isOnline = channel.toLowerCase().includes('go') || channel.toLowerCase().includes('grab') || channel.toLowerCase().includes('shopee') || channel.toLowerCase().includes('mart') || channel.toLowerCase().includes('online');
    const orderType = isOnline ? 'Delivery' : 'Takeaway';
    
    // Map destination city based on branch
    const destinationCity = branch.toLowerCase().includes('utama') ? 'Jakarta' : branch.toLowerCase().includes('timur') ? 'Surabaya' : 'Bandung';

    parsedData.push({
      date: dateStr,
      product: product,
      category: category,
      channel: channel,
      qty: qty,
      sales: sales,
      cogs: cogs,
      payment_method: payMethod === 'Tunai' ? 'Tunai' : 'E-Wallet',
      payment_provider: payMethod,
      shipping_courier: isOnline ? (Math.random() < 0.5 ? 'Gosend' : 'GrabExpress') : '',
      shipping_fee: isOnline ? 12000 : 0,
      promo_code: discount > 0 ? 'PROMORETAIL' : '',
      discount_amount: discount,
      customer_type: getCustomerType(customerId),
      table_number: '',
      variant: brand,
      destination_city: destinationCity,
      staff: cashier,
      duration: 0,
      order_type: orderType
    });
    
    // Process all valid rows as requested
  }
  
  console.log(`Successfully parsed ${parsedData.length} records.`);
  
  // Format as a TypeScript constant export
  const outputCode = `// Autogenerated from dataset_umkm_retail_kompleks_jan_mei_2026.xlsx
export interface DemoTransaction {
  date: string;
  product: string;
  category: string;
  channel: string;
  qty: number;
  sales: number;
  cogs: number;
  payment_method: string;
  payment_provider: string;
  shipping_courier: string;
  shipping_fee: number;
  promo_code: string;
  discount_amount: number;
  customer_type: string;
  table_number: string;
  variant: string;
  destination_city: string;
  staff: string;
  duration: number;
  order_type: string;
}

export const retailDemoData: DemoTransaction[] = ${JSON.stringify(parsedData, null, 2)};
export default retailDemoData;
`;

  fs.writeFileSync('src/constants/retailDemoData.ts', outputCode);
  console.log('Saved output to src/constants/retailDemoData.ts');
  
} catch (error) {
  console.error('Error running parser script:', error);
  process.exit(1);
}
