import { FileText, Printer, Upload } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { analyzeWorkspace, loadWorkspace } from '../../storage/clientWorkspace';
import { formatNumber, formatRupiah } from '../../utils/formatting';

export default function ClientReportsPage() {
  const navigate = useNavigate();
  const workspace = loadWorkspace();
  const analytics = workspace ? analyzeWorkspace(workspace) : null;
  if (!workspace || !analytics) return <div className="space-y-6"><h1 className="text-xl font-bold text-gray-900">Laporan</h1><div className="rounded-xl border border-gray-200 bg-white px-6 py-16 text-center"><FileText className="mx-auto h-12 w-12 text-gray-300" /><h2 className="mt-4 text-lg font-bold text-gray-900">Belum ada laporan</h2><p className="mt-2 text-sm text-gray-600">Upload dataset untuk membuat laporan analitik.</p><button onClick={() => navigate('/upload')} className="mt-5 inline-flex items-center gap-2 rounded-lg bg-[#276749] px-4 py-2 text-sm font-semibold text-white"><Upload className="h-4 w-4" /> Upload Data</button></div></div>;
  const top = analytics.charts.topProducts.slice(0, 5);
  return <div className="space-y-5"><div className="flex items-end justify-between gap-3 print:hidden"><div><h1 className="text-xl font-bold text-gray-900">Laporan</h1><p className="mt-0.5 text-sm text-gray-600">Ringkasan siap cetak dari dataset aktif.</p></div><button onClick={() => window.print()} className="inline-flex items-center gap-2 rounded-lg bg-[#276749] px-4 py-2 text-sm font-semibold text-white hover:bg-[#1f533a]"><Printer className="h-4 w-4" /> Cetak / Simpan PDF</button></div><article className="rounded-xl border border-gray-200 bg-white p-6 print:border-0 print:p-0"><header className="border-b border-gray-200 pb-5"><p className="text-sm font-semibold text-[#276749]">DashInsight Analytics Report</p><h2 className="mt-1 text-2xl font-bold text-gray-900">{workspace.datasetName}</h2><p className="mt-1 text-sm text-gray-600">Dibuat {new Date().toLocaleString('id-ID')} · {workspace.rows.length.toLocaleString('id-ID')} baris</p></header><section className="grid gap-3 py-5 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Total omzet" value={formatRupiah(analytics.kpis.totalOmzet)} /><Metric label="Transaksi" value={formatNumber(analytics.kpis.totalTransaksi)} /><Metric label="AOV" value={formatRupiah(analytics.kpis.avgTransaksi)} /><Metric label="Profit margin" value={`${analytics.kpis.profitMargin.toFixed(1)}%`} /></section><section className="border-t border-gray-200 py-5"><h3 className="font-bold text-gray-900">Executive Summary</h3><p className="mt-2 text-sm leading-6 text-gray-700">Dataset mencatat omzet {formatRupiah(analytics.kpis.totalOmzet)} dari {formatNumber(analytics.kpis.totalTransaksi)} transaksi. Nilai transaksi rata-rata adalah {formatRupiah(analytics.kpis.avgTransaksi)} dengan skor kualitas data {analytics.dataHealth.score}/100 ({analytics.dataHealth.label}).</p></section><section className="border-t border-gray-200 py-5"><h3 className="font-bold text-gray-900">Produk Teratas</h3><div className="mt-3 divide-y divide-gray-100">{top.map((item, index) => <div key={item.name} className="flex justify-between gap-3 py-2 text-sm"><span className="text-gray-700">{index + 1}. {item.name}</span><strong>{formatRupiah(item.sales)}</strong></div>)}</div></section><section className="border-t border-gray-200 py-5"><h3 className="font-bold text-gray-900">Temuan</h3><ul className="mt-3 list-disc space-y-2 pl-5 text-sm leading-6 text-gray-700">{analytics.insights.slice(0, 6).map((insight, index) => <li key={index}>{insight.text}</li>)}</ul></section><footer className="border-t border-gray-200 pt-4 text-xs text-gray-500">Data transaksi tetap disimpan secara lokal di perangkat pengguna.</footer></article></div>;
}
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-lg bg-gray-50 p-3"><p className="text-xs text-gray-600">{label}</p><p className="mt-1 font-bold text-gray-900">{value}</p></div>; }